### ISSUE TITLE
Change wording from "Invalid choice!"

### ISSUE THREAD

**Issue by j12y** [PredixDev/predix-cli#1]
The error message here could be made more clear.

```
root@8e97ea1b3c76:/home/app# predix login
1. US-West
2. US-East
3. Japan
4. UK

Choose the PoP to set> US-West
Invalid choice!
```

Possibly make it, "Invalid choice, please select a point of presence by entering the corresponding number."  Alternatively accept case-insensitive text in lieu of the number entry.

Bonus points to make i18n messages for errors.

**Comment by turnerth** [comment]
updated in develop.  will go out in next release.
