### ISSUE TITLE
Error when trying to create a timeseries instance "px cs predix-timeseries"

### ISSUE THREAD

**Issue by edgar-mercado** [PredixDev/predix-cli#3]
I am getting the following error when trying to create a timeseries instance
**Invalid status response: 400. authorization_code grant type requires at least one redirect URL.**

```
$ px cs predix-timeseries Free test-pm-92929292-time-series test-pm-92929292-uaa --client-id app_client_id --client-secret secret

Checking if client app_client_id exists on service instance test-pm-92929292-uaa
Client app_client_id does not exist. It will be created with the required authorities.

Creating service instance test-pm-92929292-time-series in org predix-support / space refApp as edgar.mercado@ge.com
OK

Creating client app_client_id on Predix UAA instance test-pm-92929292-uaa
FAILED
Invalid status response: 400. authorization_code grant type requires at least one redirect URL.
```

**Comment by turnerth** [comment]
Hi, we noticed that too.  It's related to a recent change in UAA.  The fix for the CLI is being tested now and should be out by eod tomorrow.

**Comment by maxceem** [comment]
I'm also facing the same issue when trying to create an asset service
```
 px cs predix-asset ...
...
FAILED
Invalid status response: 400. authorization_code grant type requires at least one redirect URL.
```

I've checked release page, it looks like there is a new release but no files to download http://joxi.ru/823Gy4t6wLYJ2O

Is it possible that there is any quick workaround as long as a new version with fix is not published?

**Comment by turnerth** [comment]
Right, it'll be true for all of the create-service commands.  The cf cli is still a possibility for you.  You'll need to set up the UAA clientId manually though.

We tried releasing earlier and found our Jenkins server has an old version of Go on it.  We are seeking resolution on that.  Apologies for the delay.

**Comment by turnerth** [comment]
The new version is out, please upgrade.
