### ISSUE TITLE
No predix.exe file when I extracted the Predix-cli for Windows. 

### ISSUE THREAD

**Issue by ghost** [PredixDev/predix-cli#4]
Hello,
I am trying to add the predix cli command line utility, but unable to follow the ReadMe instructions, there is no predix.exe file when the predix-cli.tar.gz file is extracted. Any help would be great! Is there an older version that I can use? I am working on Windows 10.

**Comment by turnerth** [comment]
just pushed a new version a few minutes ago, maybe there's a problem, will try on a windows 10 system, will get back to you.

**Comment by turnerth** [comment]
I just downloaded the latest release and in the bin/win64 directory I see the predix.exe.
