### ISSUE TITLE
No install file

### ISSUE THREAD

**Issue by whossname** [PredixDev/predix-cli#6]
I would expect this repository to contain a install.sh or install.exe file based on the install instructions (probably both?), but the repository seems to contain neither. Am I missing something? How do I install/update the Predix CLI?

**Comment by whossname** [comment]
FYI the only three files I see are LICENSE.md, README.md, and VERSION

**Comment by gstroup** [comment]
The installer is found under the "Releases" tab of github:
https://github.com/PredixDev/predix-cli/releases

**Comment by whossname** [comment]
OK, the .tar.gz file has the installer, the other two just have the three text files above. I must have downloaded one of the other files. Thanks.
